# setup.py
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from distutils.core import setup

long_description = """
ulvl provides classes for loading and saving generic level formats.  It
can be used to develop a generic level editor, and to load levels into a
game generated by such an editor.  Basic support for loading the Tiled
TMX format is also provided, enabling use of Tiled with your game.
""".strip()

setup(name="ulvl",
      version="1.0",
      description="Universal level formats library.",
      long_description=long_description,
      author="Layla Marchant",
      author_email="diligentcircle@riseup.net",
      url="https://ulvl.github.io",
      classifiers=["Development Status :: 5 - Production/Stable",
                   "License :: DFSG approved",
                   "License :: OSI Approved :: Apache Software License",
                   "Operating System :: OS Independent",
                   "Programming Language :: Python :: 3",
                   "Topic :: Games/Entertainment",
                   "Topic :: Software Development"],
      license="Apache License 2.0",
      packages=["ulvl"],
      package_dir={"ulvl": "ulvl"},
      package_data={"ulvl": ["COPYING"]},
     )
